In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('/content/creditcard.csv')

In [3]:
df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
5,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0.0
6,4,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0.0
7,7,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0.0
8,7,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0.0
9,9,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0.0

In [5]:
df.tail(6)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
105061,69348,1.213608,-0.174234,1.169714,0.709168,-1.135783,-0.429036,-0.682396,0.074934,0.923608,...,0.081159,0.384932,-0.038436,0.443456,0.311484,0.575210,0.002770,0.021089,0.01,0.0
105062,69348,1.255690,-1.393540,0.692738,-1.289430,-1.682706,-0.276840,-1.136732,-0.076399,-1.738348,...,0.039513,0.368717,-0.072065,0.106986,0.257991,-0.087901,0.054217,0.043817,116.00,0.0
105063,69349,-1.250199,0.123183,1.051709,-0.236427,1.611834,0.284241,0.288190,0.303990,-0.430526,...,0.034681,-0.039897,-0.049460,-1.399614,0.217418,-0.496523,-0.042176,0.161224,3.99,0.0
105064,69349,-1.925153,-0.140133,2.456659,0.148112,-0.284164,-0.150520,-1.129736,1.003991,-0.218409,...,0.447094,0.895815,-0.233737,0.262490,0.050375,0.515140,0.207773,-0.090777,4.69,0.0
105065,69349,1.277856,-0.027651,0.249167,0.697814,-0.232188,-0.118324,-0.145313,-0.048568,0.677505,...,-0.141950,-0.164073,-0.194695,-0.381716,0.696330,0.489582,-0.017759,0.002991,10.00,0.0
105066,69350,-1.176438,0.811442,0.539281,-1.505794,0.401363,0.202677,0.284898,0.547988,-0.438512,...,0.077511,0.008094,-0.020608,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105067 entries, 0 to 105066
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    105067 non-null  int64
 1   V1      105067 non-null  float64
 2   V2      105067 non-null  float64
 3   V3      105067 non-null  float64
 4   V4      105067 non-null  float64
 5   V5      105067 non-null  float64
 6   V6      105067 non-null  float64
 7   V7      105067 non-null  float64
 8   V8      105067 non-null  float64
 9   V9      105067 non-null  float64
 10  V10     105067 non-null  float64
 11  V11     105067 non-null  float64
 12  V12     105067 non-null  float64
 13  V13     105067 non-null  float64
 14  V14     105067 non-null  float64
 15  V15     105067 non-null  float64
 16  V16     105067 non-null  float64
 17  V17     105067 non-null  float64
 18  V18     105067 non-null  float64
 19  V19     105067 non-null  float64
 20  V20     105067 non-null  float64
 21  V21     105067 non-null  float64
 22  V22     105067 non-null  float64
 23  V23     105067 non-null  float64
 24  V24     105066 non-null  float64
 25  V25     105066 non-null  float64
 26  V26     105066 non-null  float64
 27  V27     105066 non-null  float64
 28  V28     105066 non-null  float64
 29  Amount  105066 non-null  float64
 30  Class   105066 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 24.8 MB

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
df.shape

(105067, 31)

In [10]:
df['Class'].value_counts()

0.0    104834
1.0       232
Name: Class, dtype: int64

separating  the data for analysis

In [13]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [14]:
print(legit.shape)

(104834, 31)

In [15]:
print(fraud.shape)

(232, 31)

In [16]:
legit.Amount.describe()

count    104834.000000
mean         96.584297
std         262.333583
min           0.000000
25%           7.190000
50%          25.540000
75%          87.440000
max       19656.530000
Name: Amount, dtype: float64

In [17]:
fraud.Amount.describe()

count     232.000000
mean      115.520474
std       253.721393
min         0.000000
25%         1.000000
50%         7.595000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [18]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,43692.851508,-0.245296,-0.039251,0.702486,0.146715,-0.274535,0.102607,-0.102664,0.053767,-0.044415,...,0.043860,-0.032987,-0.104940,-0.037011,0.010118,0.133410,0.025912,0.000488,0.001663,96.584297
1.0,37898.655172,-6.138432,4.280104,-7.850475,4.800030,-4.349687,-1.566011,-6.505922,1.640373,-2.788880,...,0.237631,1.386881,-0.351377,-0.114210,-0.118153,0.208771,0.094034,0.536235,0.061592,115.520474

UNDER SAMPLING

In [19]:
#number of fraud transaction ---> 232

In [20]:
legit_sample = legit.sample(n=232)

In [25]:
dv = pd.concat([legit_sample, fraud] , axis=0)

In [26]:
dv.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7424,10039,-0.967606,1.511021,0.907589,0.220591,-0.173251,-0.563367,0.106571,0.481507,1.075712,...,-0.388742,-0.886567,0.094876,-0.071442,-0.220741,0.073636,0.217636,0.073191,8.99,0.0
84779,60460,-1.525953,1.431936,0.635212,-1.542051,-0.655350,-0.713662,-0.035825,0.660727,0.619229,...,-0.201640,-0.363426,0.001078,-0.015839,-0.141532,0.692619,-0.100452,-0.339725,1.46,0.0
56727,47559,1.257949,-0.110579,0.317390,-0.172948,-0.160743,0.120605,-0.326425,0.045745,0.368250,...,-0.215026,-0.602318,0.045445,-0.837775,0.078254,0.874731,-0.046720,0.005443,20.56,0.0
54568,46508,1.225944,-0.532659,-0.274676,0.263986,-0.071462,0.461999,-0.288407,0.003848,-0.943337,...,-0.304576,-0.532805,-0.247102,-1.370792,0.634752,-0.171005,0.040168,0.024270,94.69,0.0
28938,35244,-1.335418,0.533593,2.020291,-0.972948,-0.782193,-0.085502,-0.448361,0.851564,0.174530,...,0.146550,0.288162,-0.289020,0.051418,0.265589,1.060527,0.086156,0.014590,17.05,0.0
94353,64841,-3.759296,3.295790,0.424933,-0.509604,-1.046192,-1.172559,0.481983,-0.430778,1.698510,...,-0.102633,-0.569623,0.198361,0.860251,-0.232520,-0.230984,-2.178945,-0.353651,8.99,0.0
83211,59736,-1.966907,-1.154106,1.449016,0.894238,-0.963885,-0.737885,-0.355940,0.452712,-1.354627,...,0.127230,0.223647,0.386615,0.716424,-0.049075,-0.211247,0.285154,-0.032264,214.00,0.0
30115,35779,-0.908173,0.202760,0.458577,-1.822204,-0.180609,-0.828805,0.249730,0.067145,-0.645817,...,0.181122,0.757242,-0.021885,-0.018575,-0.129694,-0.307181,0.593313,0.395593,20.00,0.0
55669,47060,-2.256772,-1.082271,1.345092,-3.528973,-0.550470,0.256259,-0.182229,-0.651620,0.223318,...,0.278213,-0.553440,0.471554,-0.865762,0.396126,-0.179413,-0.508035,-0.306499,110.00,0.0
94264,64807,-0.809776,0.561517,1.335707,1.390096,0.150153,-0.135270,0.345021,0.220268,0.186409,...,-0.069854,0.082346,0.137337,0.023775,-0.123005,-0.216595,0.313771,0.178605,9.46,0.0

In [27]:
dv.tail(8)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
101509,67857,-1.739334,-1.304655,0.314103,0.053740,-0.058696,0.071260,0.694862,-0.313270,-0.649377,...,-0.665172,-0.632078,-0.421176,-0.400774,-0.001640,-0.495162,0.031633,0.066280,320.00,1.0
102441,68207,-13.192671,12.785971,-9.906650,3.320337,-4.801176,5.760059,-18.750889,-37.353443,-0.391540,...,27.202839,-8.887017,5.303607,-0.639435,0.263203,-0.108877,1.269566,0.939407,1.00,1.0
102442,68207,-13.192671,12.785971,-9.906650,3.320337,-4.801176,5.760059,-18.750889,-37.353443,-0.391540,...,27.202839,-8.887017,5.303607,-0.639435,0.263203,-0.108877,1.269566,0.939407,1.00,1.0
102443,68207,-13.192671,12.785971,-9.906650,3.320337,-4.801176,5.760059,-18.750889,-37.353443,-0.391540,...,27.202839,-8.887017,5.303607,-0.639435,0.263203,-0.108877,1.269566,0.939407,1.00,1.0
102444,68207,-13.192671,12.785971,-9.906650,3.320337,-4.801176,5.760059,-18.750889,-37.353443,-0.391540,...,27.202839,-8.887017,5.303607,-0.639435,0.263203,-0.108877,1.269566,0.939407,1.00,1.0
102445,68207,-13.192671,12.785971,-9.906650,3.320337,-4.801176,5.760059,-18.750889,-37.353443,-0.391540,...,27.202839,-8.887017,5.303607,-0.639435,0.263203,-0.108877,1.269566,0.939407,1.00,1.0
102446,68207,-13.192671,12.785971,-9.906650,3.320337,-4.801176,5.760059,-18.750889,-37.353443,-0.391540,...,27.202839,-8.887017,5.303607,-0.639435,0.263203,-0.108877,1.269566,0.939407,1.00,1.0
102782,68357,1.232604,-0.548931,1.087873,0.894082,-1.433055,-0.356797,-0.717492,0.003167,-0.100397,...,-0.448671,-0.517568,0.012833,0.699217,0.527258,-0.322607,0.080805,0.035427,19.59,1.0

In [28]:
dv['Class'].value_counts()

0.0    232
1.0    232
Name: Class, dtype: int64

In [29]:
dv.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,44004.793103,-0.267472,-0.050045,0.750281,0.109608,-0.289703,0.252670,0.075131,0.067700,-0.08067,...,0.100456,0.027762,-0.076613,0.023683,-0.012886,0.148009,-0.010570,-0.015961,0.003908,123.112284
1.0,37898.655172,-6.138432,4.280104,-7.850475,4.800030,-4.349687,-1.566011,-6.505922,1.640373,-2.78888,...,0.237631,1.386881,-0.351377,-0.114210,-0.118153,0.208771,0.094034,0.536235,0.061592,115.520474

SPLITTING THE DATA INTO FEATURE AND TARGET

In [31]:
X = dv.drop(columns='Class', axis=1)
Y = dv['Class']

In [32]:
print(X)

         Time         V1         V2        V3        V4        V5        V6  \
7424    10039  -0.967606   1.511021  0.907589  0.220591 -0.173251 -0.563367
84779   60460  -1.525953   1.431936  0.635212 -1.542051 -0.655350 -0.713662
56727   47559   1.257949  -0.110579  0.317390 -0.172948 -0.160743  0.120605
54568   46508   1.225944  -0.532659 -0.274676  0.263986 -0.071462  0.461999
28938   35244  -1.335418   0.533593  2.020291 -0.972948 -0.782193 -0.085502
...       ...        ...        ...       ...       ...       ...       ...
102443  68207 -13.192671  12.785971 -9.906650  3.320337 -4.801176  5.760059
102444  68207 -13.192671  12.785971 -9.906650  3.320337 -4.801176  5.760059
102445  68207 -13.192671  12.785971 -9.906650  3.320337 -4.801176  5.760059
102446  68207 -13.192671  12.785971 -9.906650  3.320337 -4.801176  5.760059
102782  68357   1.232604  -0.548931  1.087873  0.894082 -1.433055 -0.356797

               V7         V8        V9  ...       V20        V21       V22  \
7424     0.106571   0.481507  1.075712  ... -0.016479  -0.388742 -0.886567
84779   -0.035825   0.660727  0.619229  ...  0.243366  -0.201640 -0.363426
56727   -0.326425   0.045745  0.368250  ...  0.004059  -0.215026 -0.602318
54568   -0.288407   0.003848 -0.943337  ... -0.368154  -0.304576 -0.532805
28938   -0.448361   0.851564  0.174530  ... -0.024014   0.146550  0.288162
...           ...        ...       ...  ...       ...        ...       ...
102443 -18.750889 -37.353443 -0.391540  ... -3.493050  27.202839 -8.887017
102444 -18.750889 -37.353443 -0.391540  ... -3.493050  27.202839 -8.887017
102445 -18.750889 -37.353443 -0.391540  ... -3.493050  27.202839 -8.887017
102446 -18.750889 -37.353443 -0.391540  ... -3.493050  27.202839 -8.887017
102782  -0.717492   0.003167 -0.100397  ... -0.576274  -0.448671 -0.517568

             V23       V24       V25       V26       V27       V28  Amount
7424    0.094876 -0.071442 -0.220741  0.073636  0.217636  0.073191    8.99
84779   0.001078 -0.015839 -0.141532  0.692619 -0.100452 -0.339725    1.46
56727   0.045445 -0.837775  0.078254  0.874731 -0.046720  0.005443   20.56
54568  -0.247102 -1.370792  0.634752 -0.171005  0.040168  0.024270   94.69
28938  -0.289020  0.051418  0.265589  1.060527  0.086156  0.014590   17.05
...          ...       ...       ...       ...       ...       ...     ...
102443  5.303607 -0.639435  0.263203 -0.108877  1.269566  0.939407    1.00
102444  5.303607 -0.639435  0.263203 -0.108877  1.269566  0.939407    1.00
102445  5.303607 -0.639435  0.263203 -0.108877  1.269566  0.939407    1.00
102446  5.303607 -0.639435  0.263203 -0.108877  1.269566  0.939407    1.00
102782  0.012833  0.699217  0.527258 -0.322607  0.080805  0.035427   19.59

[464 rows x 30 columns]

In [33]:
print(Y)

7424      0.0
84779     0.0
56727     0.0
54568     0.0
28938     0.0
         ...
102443    1.0
102444    1.0
102445    1.0
102446    1.0
102782    1.0
Name: Class, Length: 464, dtype: float64

SPLIT THE DATA INTO  TRAINING DATA NAD TESTING DATA

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X ,Y , test_size =0.2 ,stratify=Y , random_state=2)

In [35]:
print(X.shape, X_train.shape,X_test.shape)

(464, 30) (371, 30) (93, 30)

MODEL TRAINING

In [36]:
model = LogisticRegression()

In [37]:
model.fit(X_train,Y_train)

LogisticRegression()

In [39]:
X_train_prediction = model.predict(X_train)

In [40]:
print(X_train_prediction)

[0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.
 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0.
 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0.
 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0.
 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0.
 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0.
 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0.
 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0.
 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0.]

In [42]:
training_data_accuracy = accuracy_score(Y_train , X_train_prediction)
print('Accuracy score of training data :',training_data_accuracy)

Accuracy score of training data : 0.954177897574124

In [43]:
X_test_prediction = model.predict(X_test)

In [44]:
print(X_test_prediction)

[0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1.
 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0.
 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.
 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0.]

In [45]:
test_data_accuracy = accuracy_score(Y_test , X_test_prediction)
print('Accuracy score of test data :',test_data_accuracy)

Accuracy score of test data : 0.946236559139785